#!/usr/bin/env php
<?php
/**
 * ZF2 command line tool
 *
 * @link      http://github.com/zendframework/ZFTool for the canonical source repository
 * @copyright Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */
$basePath = getcwd();

define('APP_ROOT', __DIR__);
defined('APP_ENVIRONMENT') ||
define('APP_ENVIRONMENT', isset($_ENV['APP_ENVIRONMENT']) ? $_ENV['APP_ENVIRONMENT'] : (
isset($_SERVER['APP_ENVIRONMENT']) ? $_SERVER['APP_ENVIRONMENT'] : 'production'
));

ini_set('user_agent', 'BirdSystem Command Line Interface');

// load autoloader
if (file_exists("$basePath/vendor/autoload.php")) {
    require_once "$basePath/vendor/autoload.php";
} elseif (\Phar::running()) {
    require_once __DIR__ . '/vendor/autoload.php';
} else {
    echo 'Error: I cannot find the autoloader of the application.' . PHP_EOL;
    echo "Check if $basePath contains a valid application." . PHP_EOL;
    exit(2);
}

$appConfig = [
    'modules' => [
        'Zend\Mvc\Console',
        'Zend\Router',
        'BS\CLI'
    ],
    'module_listener_options' => [
        'config_glob_paths' => [
            'config/autoload/{,*.}{global,local}.php',
        ],
        'module_paths' => [
            './module'
        ],
    ],
];

Zend\Mvc\Application::init($appConfig)->run();
